# Alembic migration template (Mako). Used by `alembic revision` to
# generate new migration files. Do not edit unless customizing the
# generated file format.
"""create service schema

Revision ID: 88ea31070844
Revises: 
Create Date: 2026-05-17 20:51:24.890885
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88ea31070844'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('app_key', sa.Text(), nullable=False),
    sa.Column('app_secret', sa.Text(), nullable=False),
    sa.Column('account_no', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('condition', sa.Text(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), nullable=True),
    sa.Column('post_mortem', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('idx_alerts_triggered', [sa.literal_column('triggered_at DESC')], unique=False)

    op.create_table('batch_analysis_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.Date(), nullable=False),
    sa.Column('strategy_name', sa.Text(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('llm_commentary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_date', 'strategy_name', 'stock_code'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('batch_analysis_results', schema=None) as batch_op:
        batch_op.create_index('idx_batch_date', [sa.literal_column('analysis_date DESC'), 'rank'], unique=False)

    op.create_table('llm_cache',
    sa.Column('cache_key', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_key')
    )
    op.create_table('principles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('is_editable', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_table('settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('watchlist_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), server_default=sa.text("'#888888'"), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sqlite_autoincrement=True
    )
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('kis_order_no', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['account_type'], ['accounts.type'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.create_index('idx_trades_account_executed', ['account_type', sa.literal_column('executed_at DESC')], unique=False)
        batch_op.create_index('idx_trades_stock', ['stock_code'], unique=False)

    op.create_table('watchlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['watchlist_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'category_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.create_index('idx_watchlist_stock', ['stock_code'], unique=False)

    op.create_table('trade_journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('post_review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_id'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('trade_journal', schema=None) as batch_op:
        batch_op.create_index('idx_journal_trade', ['trade_id'], unique=False)

    op.create_table('trade_journal_principles',
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('principle_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['trade_journal.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['principle_id'], ['principles.id'], ),
    sa.PrimaryKeyConstraint('journal_id', 'principle_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_journal_principles')
    with op.batch_alter_table('trade_journal', schema=None) as batch_op:
        batch_op.drop_index('idx_journal_trade')

    op.drop_table('trade_journal')
    with op.batch_alter_table('watchlist_entries', schema=None) as batch_op:
        batch_op.drop_index('idx_watchlist_stock')

    op.drop_table('watchlist_entries')
    with op.batch_alter_table('trades', schema=None) as batch_op:
        batch_op.drop_index('idx_trades_stock')
        batch_op.drop_index('idx_trades_account_executed')

    op.drop_table('trades')
    op.drop_table('watchlist_categories')
    op.drop_table('settings')
    op.drop_table('principles')
    op.drop_table('llm_cache')
    with op.batch_alter_table('batch_analysis_results', schema=None) as batch_op:
        batch_op.drop_index('idx_batch_date')

    op.drop_table('batch_analysis_results')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('idx_alerts_triggered')

    op.drop_table('alerts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
