"""Realistic trade execution helpers for Korean equity backtests."""

from __future__ import annotations

from datetime import date as Date

from pydantic import BaseModel, Field


class CostModel(BaseModel):
    """KRX-style transaction cost assumptions."""

    commission_rate: float = 0.00015
    sell_tax_rate: float = 0.0023
    slippage_bps: float = 10.0


class SimulatedTrade(BaseModel):
    """One simulated execution generated by a rebalance."""

    date: Date
    code: str
    side: str
    qty: int
    price: float
    notional: float
    commission: float
    tax: float
    slippage_bps: float
    cash_flow: float = Field(
        description="Positive for sell proceeds, negative for buy cash usage."
    )


def execute_trade(
    *,
    code: str,
    side: str,
    qty: int,
    close_price: float,
    trade_date: Date,
    cost_model: CostModel | None = None,
) -> SimulatedTrade | None:
    """Execute one order at close plus side-aware slippage and costs."""

    if qty <= 0 or close_price <= 0:
        return None

    model = cost_model or CostModel()
    normalized_side = side.upper()
    if normalized_side not in {"BUY", "SELL"}:
        raise ValueError(f"Unsupported side: {side}")

    slippage_multiplier = model.slippage_bps / 10_000
    if normalized_side == "BUY":
        fill_price = close_price * (1 + slippage_multiplier)
    else:
        fill_price = close_price * (1 - slippage_multiplier)

    notional = fill_price * qty
    commission = notional * model.commission_rate
    tax = notional * model.sell_tax_rate if normalized_side == "SELL" else 0.0

    if normalized_side == "BUY":
        cash_flow = -(notional + commission)
    else:
        cash_flow = notional - commission - tax

    return SimulatedTrade(
        date=trade_date,
        code=code,
        side=normalized_side,
        qty=qty,
        price=fill_price,
        notional=notional,
        commission=commission,
        tax=tax,
        slippage_bps=model.slippage_bps,
        cash_flow=cash_flow,
    )


def rebalance(
    *,
    current: dict[str, int],
    target: dict[str, int],
    prices: dict[str, float],
    trade_date: Date,
    cost_model: CostModel | None = None,
) -> list[SimulatedTrade]:
    """Translate current-vs-target position diffs into simulated trades."""

    trades: list[SimulatedTrade] = []
    all_codes = sorted(set(current) | set(target))
    model = cost_model or CostModel()

    for code in all_codes:
        price = prices.get(code)
        if price is None or price <= 0:
            continue

        diff = target.get(code, 0) - current.get(code, 0)
        if diff == 0:
            continue

        trade = execute_trade(
            code=code,
            side="BUY" if diff > 0 else "SELL",
            qty=abs(diff),
            close_price=price,
            trade_date=trade_date,
            cost_model=model,
        )
        if trade is not None:
            trades.append(trade)

    # Sell first so cash is available for buys on the same rebalance date.
    return sorted(trades, key=lambda trade: 0 if trade.side == "SELL" else 1)
