# Alembic migration template (Mako). Used by `alembic revision` to
# generate new migration files. Do not edit unless customizing the
# generated file format.
"""create research schema

Revision ID: bc1fc0ca2a36
Revises: 
Create Date: 2026-05-17 20:51:28.239697
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc1fc0ca2a36'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_index',
    sa.Column('index_code', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.PrimaryKeyConstraint('index_code', 'date')
    )
    op.create_table('stocks',
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('market', sa.Text(), nullable=False),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('listed_at', sa.Date(), nullable=False),
    sa.Column('delisted_at', sa.Date(), nullable=True),
    sa.Column('is_delisted', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index('idx_stocks_delisted', ['is_delisted'], unique=False)
        batch_op.create_index('idx_stocks_market', ['market'], unique=False)

    op.create_table('factor_values',
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('factor_name', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('stock_code', 'date', 'factor_name')
    )
    with op.batch_alter_table('factor_values', schema=None) as batch_op:
        batch_op.create_index('idx_factor_date', ['date', 'factor_name'], unique=False)

    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('fiscal_period', sa.Date(), nullable=False),
    sa.Column('disclosed_at', sa.Date(), nullable=False),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('operating_income', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('total_assets', sa.Numeric(), nullable=True),
    sa.Column('total_equity', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('bps', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_code', 'fiscal_period'),
    sqlite_autoincrement=True
    )
    with op.batch_alter_table('financials', schema=None) as batch_op:
        batch_op.create_index('idx_fin_stock_disclosed', ['stock_code', 'disclosed_at'], unique=False)

    op.create_table('prices_daily',
    sa.Column('stock_code', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=False),
    sa.Column('high', sa.Numeric(), nullable=False),
    sa.Column('low', sa.Numeric(), nullable=False),
    sa.Column('close', sa.Numeric(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('adj_close', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['stock_code'], ['stocks.code'], ),
    sa.PrimaryKeyConstraint('stock_code', 'date')
    )
    with op.batch_alter_table('prices_daily', schema=None) as batch_op:
        batch_op.create_index('idx_prices_date', ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prices_daily', schema=None) as batch_op:
        batch_op.drop_index('idx_prices_date')

    op.drop_table('prices_daily')
    with op.batch_alter_table('financials', schema=None) as batch_op:
        batch_op.drop_index('idx_fin_stock_disclosed')

    op.drop_table('financials')
    with op.batch_alter_table('factor_values', schema=None) as batch_op:
        batch_op.drop_index('idx_factor_date')

    op.drop_table('factor_values')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index('idx_stocks_market')
        batch_op.drop_index('idx_stocks_delisted')

    op.drop_table('stocks')
    op.drop_table('market_index')
    # ### end Alembic commands ###
